### PR TITLE
Fixed typo in eBayes.Rd

### PR DESCRIPTION
**Pull request by idblr**
Value 'RRmed' is the ecological relative risk posterior median estimates while 'RR' is the ecological relative risk posterior mean estimates

### CODE REVIEW

**Comment by idblr** [comment]
The 'RRmed' is not the median estimates. Definitely a typo as the description for 'RR' and 'RRmed' are duplicated

**Comment by rudeboybert** [comment]
Thanks @idblr, could you reopen the PR?

**Comment by idblr** [comment]
@rudeboybert Certainly! Apologies, I believe I misinterpreted 'RRmed' as a median. I will reopen

**Comment by rudeboybert** [comment]
thanks!

**Comment by rudeboybert** [comment]
FYI here is the relevant line of code: https://github.com/rudeboybert/SpatialEpi/blob/master/R/eBayes.R#L17

**Pull request merged**
