### PR TITLE
converted NYleukemia to sf object and wrote documentation

### PR DESCRIPTION
**Pull request by arrismo**

### CODE REVIEW

**Comment by arrismo** [comment]
@rudeboybert  where can I find context for the variables of NYleukemia ? I went to the site referenced but it was not helpful.

**Comment by rudeboybert** [comment]
Alas if its not in the original `?NYleukemia` file, then I don't know off the top of my head. Is there a specific thing you wish you knew?

Also let me hold off on reviewing this code until you've had a chance to go over my review of `pennLC_sf`. But at first glance what you have so far looks 🎯

**Comment by rudeboybert** [comment]
Note that FIPS codes are https://www.policymap.com/2012/08/tips-on-fips-a-quick-guide-to-geographic-place-codes-part-iii/

**Review by rudeboybert — APPROVED** [review]

**Comment by rudeboybert** [comment]
Looks great!

**Pull request merged**
